# Rebuild the larger, explicitly simulated Studio macro examples.
# Run from the package root: Rscript data-raw/studio_simulated.R
# These are format-compatible demonstration files, not software analysis output.
set.seed(5001)
options(scipen = 999)
out <- "inst/extdata"
genomes <- paste0("Sim", LETTERS[1:4])
lengths <- c(32, 29, 26, 23, 21, 19, 17, 15) * 1e6
scales <- c(1, 1.08, 0.94, 1.15)
n_genes <- 160L
genes <- list()
truth <- list()
for (g in seq_along(genomes)) for (chr in seq_along(lengths)) {
  size <- round(lengths[chr] * scales[g])
  ends <- round(seq(12000, size, length.out = n_genes))
  rows <- data.frame(chr = paste0(genomes[g], chr),
                      gene = sprintf("%s_chr%02d_g%04d", genomes[g], chr, seq_len(n_genes)),
                      start = ends - sample(1500:8000, n_genes, replace = TRUE), end = ends)
  genes[[paste(genomes[g], chr, sep = "_")]] <- rows
  truth[[length(truth) + 1L]] <- data.frame(species = genomes[g], chr = chr, size = size)
}
annotation <- do.call(rbind, genes)
chromosomes <- do.call(rbind, truth)
write.table(annotation, file.path(out, "studio_mcscanx.gff"), sep = "\t",
            row.names = FALSE, col.names = FALSE, quote = FALSE)
write.table(chromosomes, file.path(out, "studio_simulated_chromosomes.tsv"),
            sep = "\t", row.names = FALSE, quote = FALSE)

pairs <- combn(genomes, 2, simplify = FALSE)
alignment_lines <- character()
linked_genes <- character()
block_id <- 0L
anchor_pairs <- 0L
orientations <- character()
for (pair_id in seq_along(pairs)) {
  pair <- pairs[[pair_id]]
  for (chr in seq_along(lengths)) for (slot in 1:5) {
    # Most blocks retain their chromosome; a regular minority are relocated.
    chr_b <- if ((pair_id + chr + slot) %% 7 == 0) chr %% length(lengths) + 1L else chr
    n <- sample(8:14, 1)
    a_start <- round(seq(8, 138, length.out = 5)[slot]) + sample(-3:3, 1)
    target_slot <- if ((pair_id + chr) %% 4 == 0) 6L - slot else slot
    b_start <- round(seq(8, 138, length.out = 5)[target_slot]) + sample(-3:3, 1)
    a <- genes[[paste(pair[1], chr, sep = "_")]][a_start + seq_len(n) - 1L, ]
    b <- genes[[paste(pair[2], chr_b, sep = "_")]][b_start + seq_len(n) - 1L, ]
    orientation <- if ((pair_id + chr + slot) %% 4 == 0) "minus" else "plus"
    if (orientation == "minus") b <- b[rev(seq_len(n)), ]
    alignment_lines <- c(alignment_lines,
      sprintf("## Alignment %d: score=%.1f e_value=0 N=%d %s&%s %s",
              block_id, n * 50, n, a$chr[1], b$chr[1], orientation),
      sprintf(" %d- %2d:\t%s\t%s\t0", block_id, seq_len(n) - 1L, a$gene, b$gene))
    linked_genes <- c(linked_genes, a$gene, b$gene)
    anchor_pairs <- anchor_pairs + n
    orientations <- c(orientations, orientation)
    block_id <- block_id + 1L
  }
}
header <- c("# SIMULATED demonstration data; not an MCScanX analysis.",
            "# Generated by data-raw/studio_simulated.R (seed 5001).",
            "############### Parameters ###############", "# MATCH_SCORE: 50",
            "# MATCH_SIZE: 5", "# GAP_PENALTY: -1", "# OVERLAP_WINDOW: 5",
            "# E_VALUE: 0.00001", "# MAX GAPS: 25",
            "############### Statistics ###############",
            sprintf("# Number of collinear genes: %d, Percentage: %.2f",
                    length(unique(linked_genes)), 100 * length(unique(linked_genes)) / nrow(annotation)),
            paste("# Number of all genes:", nrow(annotation)),
            paste("# Number of simulated anchor pairs:", anchor_pairs),
            "############################################")
writeLines(c(header, alignment_lines), file.path(out, "studio_mcscanx.collinearity"))

# synHits-compatible interval records exercise the package's existing reader.
# IDs identify simulated regions; rows are not gene-level orthology assertions.
hits <- list()
for (pair_id in seq_along(pairs)) {
  pair <- pairs[[pair_id]]
  for (chr in seq_along(lengths)) for (slot in 1:8) {
    chr_b <- if ((pair_id + chr + slot) %% 6 == 0) (chr + 1L) %% length(lengths) + 1L else chr
    n <- sample(6:11, 1)
    a_start <- round(seq(5, 145, length.out = 8)[slot]) + sample(-2:2, 1)
    target_slot <- if ((pair_id + chr) %% 5 == 0) 9L - slot else slot
    b_start <- round(seq(5, 145, length.out = 8)[target_slot]) + sample(-2:2, 1)
    a <- genes[[paste(pair[1], chr, sep = "_")]][a_start + seq_len(n) - 1L, ]
    b <- genes[[paste(pair[2], chr_b, sep = "_")]][b_start + seq_len(n) - 1L, ]
    id <- length(hits) + 1L
    hits[[id]] <- data.frame(
      ofID1 = sprintf("%s_region_%04d", pair[1], id),
      ofID2 = sprintf("%s_region_%04d", pair[2], id),
      genome1 = pair[1], genome2 = pair[2], chr1 = chr, chr2 = chr_b,
      start1 = min(a$start), end1 = max(a$end), start2 = min(b$start), end2 = max(b$end),
      isAnchor = TRUE, record_type = "simulated_interval")
  }
}
hits <- do.call(rbind, hits)
write.table(hits, file.path(out, "studio_genespace_synHits.tsv"), sep = "\t",
            row.names = FALSE, quote = FALSE)
stopifnot(nrow(chromosomes) == 32L, nrow(annotation) == 5120L,
          block_id == 240L, nrow(hits) == 384L,
          !anyDuplicated(annotation$gene), all(hits$end1 > hits$start1),
          all(hits$end2 > hits$start2))
notes <- c(
  "# Simulated Studio macro examples", "",
  "These files are generated examples, not results from biological samples or",
  "from running MCScanX or GENESPACE. Rebuild from the package root with",
  "`Rscript data-raw/studio_simulated.R` (seed 5001).", "",
  "Both examples contain four synthetic genomes, SimA through SimD, with eight",
  "chromosomes each. All six genome pairs have supplied relationships.", "",
  sprintf("- MCScanX: 240 blocks, %d anchor pairs, 5,120 annotated genes.", anchor_pairs),
  sprintf("  %d plus / %d minus blocks; minus blocks reverse anchor order.",
          sum(orientations == "plus"), sum(orientations == "minus")),
  "- GENESPACE: 384 synHits-compatible simulated interval matches. Region IDs",
  "  describe intervals, not inferred gene-level orthology. These exercise the",
  "  existing coordinate parser; they do not reproduce the GENESPACE algorithm.",
  "- Both include same-chromosome conservation and interchromosomal matches.",
  "- Coordinates are integer base pairs. The existing importers convert them",
  "  to Mb. MCScanX spans extend to the final annotated gene; GENESPACE spans",
  "  are inferred from the supplied intervals and may omit terminal flanks.",
  "- studio_simulated_chromosomes.tsv records the generation bounds in bp.",
  "- Circular views show all 240 / 384 rows. With the default SimA-B-C-D order,",
  "  linear chromosome views show the 120 / 192 adjacent-genome rows.", "",
  "The small mcscanx_output.* and genespace_synHits.tsv files remain available",
  "for short parser examples and upload tests.")
writeLines(notes, file.path(out, "studio_simulated_README.md"))
cat(paste(notes[8:14], collapse = "\n"), "\n")
