test_that("the chloroplast example builds every ring and its script reproduces it", {
  grDevices::pdf(NULL); on.exit(grDevices::dev.off())
  ex <- .tracks_chloroplast()
  expect_equal(vapply(ex$tracks, `[[`, "", "geom"), c("feature", "axis", "feature", "line", "heatmap"))
  p <- .tracks_plot(.tracks_chloroplast_plot(ex, "Ring"), ex$tracks)
  expect_s3_class(p, "ggplot")
  expect_equal(length(attr(p, "synteny_tracks")), 5)
  expect_silent(ggplot2::ggplot_build(p))
  inside <- lapply(ex$tracks, function(t) { t$position <- "inside"; t })
  expect_silent(ggplot2::ggplot_build(.tracks_plot(.tracks_chloroplast_plot(ex), inside)))
  dir <- tempfile(); dir.create(dir); old <- setwd(dir); on.exit(setwd(old), add = TRUE)
  data_tracks <- .tracks_data(ex$tracks)
  expect_equal(length(data_tracks), 4)
  for (i in seq_along(data_tracks))
    write.table(data_tracks[[i]]$data, paste0("track", i, ".tsv"), sep = "\t", row.names = FALSE, quote = TRUE)
  code <- c("library(ggsynteny)", .tracks_chloroplast_code(), .tracks_code(ex$tracks))
  expect_match(paste(code, collapse = "\n"), 'track4 <- read.delim("track4.tsv")', fixed = TRUE)
  expect_false(grepl("track5", paste(code, collapse = "\n")))
  e <- new.env()
  expect_silent(eval(parse(text = code), envir = e))
  expect_equal(length(attr(e$p, "synteny_tracks")), 5)
  expect_equal(ggplot2::ggplot_build(e$p)$data, ggplot2::ggplot_build(.tracks_plot(.tracks_chloroplast_plot(ex), ex$tracks))$data)
})

test_that("uploaded track tables are typed, validated and drawn with every geom", {
  grDevices::pdf(NULL); on.exit(grDevices::dev.off())
  path <- tempfile(fileext = ".csv")
  writeLines(c("chr,start,end,value,kind,strand", "1,0,5,40,a,+", "1,5,9,NA,b,-", "1,9,12,55,a,+"), path)
  x <- .tracks_table(path)
  expect_type(x$start, "double"); expect_true(is.na(x$value[2])); expect_identical(x$chr, c("1", "1", "1"))
  expect_equal(.tracks_categories(x), "kind")
  spec <- .tracks_spec_from_table(x, "t1")
  expect_equal(spec$geom, "heatmap"); expect_equal(spec$limits, c(40, 55))
  spec2 <- .tracks_spec_from_table(x[setdiff(names(x), "value")], "t2")
  expect_equal(spec2$geom, "feature"); expect_equal(spec2$fill, "kind"); expect_equal(spec2$strand, "split")
  bad <- tempfile(fileext = ".tsv"); writeLines(c("start\tend", "a\t5"), bad)
  expect_error(.tracks_table(bad), "numeric")
  bad2 <- tempfile(fileext = ".tsv"); writeLines(c("start\tvalue", "1\t5"), bad2)
  expect_error(.tracks_table(bad2), "missing: end")
  data(rice_sorghum)
  base <- plot_circular_synteny(rice_sorghum, c("Rice", "Sorghum"))
  one <- data.frame(species = "Rice", chr = "1", start = c(0, 10, 20), end = c(10, 20, 30),
                    value = c(30, 50, 70), kind = c("a", "b", "a"), strand = c("+", "-", "+"))
  specs <- list(
    list(geom = "feature", data = one, fill = "kind", strand = "arrow", label_column = "kind", height = 0.08, gap = 0.02, position = "outside"),
    list(geom = "heatmap", data = one, name = "GC", limits = c(0, 100), height = 0.1, gap = 0.03, position = "inside"),
    list(geom = "line", data = one, name = "GC", limits = c(0, 100), reference = 50, height = 0.1, gap = 0.03),
    list(geom = "bar", data = one, name = "GC", limits = c(0, 100), height = 0.1, gap = 0.03, position = "inside"),
    list(geom = "axis", by = 10, unit = NULL, position = "outside"))
  p <- .tracks_plot(base, specs)
  expect_equal(vapply(attr(p, "synteny_tracks"), `[[`, "", "geom"), c("feature", "heatmap", "line", "bar", "axis"))
  expect_silent(ggplot2::ggplot_build(p))
  expect_silent(ggplot2::ggplot_build(.tracks_plot(plot_synteny(rice_sorghum, c("Rice", "Sorghum")), specs)))
  code <- .tracks_code(specs)
  expect_silent(parse(text = code))
  expect_match(code[length(code)], "syn_axis(by = 10, position", fixed = TRUE)
  expect_equal(sum(grepl("^track[0-9] <- read.delim", code)), 4)
})

test_that("the tracks list serves the example rings and reacts to uploads, switches and reordering", {
  skip_if_not_installed("shiny")
  grDevices::pdf(NULL); on.exit(grDevices::dev.off())
  data(rice_sorghum)
  base <- shiny::reactive(plot_circular_synteny(rice_sorghum, c("Rice", "Sorghum")))
  layout <- shiny::reactiveVal("circular")
  example <- shiny::reactiveVal(TRUE)
  shiny::testServer(.tracks_server, args = list(base_plot = base, layout = layout, example = example), {
    session$flushReact()
    expect_equal(length(active()), 5)
    expect_equal(vapply(active(), `[[`, "", "id"), c("regions", "axis", "genes", "gc", "skew"))
    session$setInputs(on_skew = FALSE)
    expect_equal(length(active()), 4)
    session$setInputs(down_regions = 1)
    expect_equal(vapply(active(), `[[`, "", "id")[1:2], c("axis", "regions"))
    session$setInputs(position_gc = "outside")
    expect_equal(Filter(function(t) t$id == "gc", active())[[1]]$position, "outside")
    expect_match(output$count, "4 of 5 on")
    example(FALSE); session$flushReact()
    expect_equal(length(active()), 0)
    path <- tempfile(fileext = ".tsv")
    writeLines(c("species\tchr\tstart\tend\tvalue\tkind", "Rice\t1\t0\t10\t40\ta", "Rice\t1\t10\t20\t60\tb"), path)
    session$setInputs(add_file = list(datapath = path, name = "t.tsv"))
    expect_equal(length(active()), 1)
    expect_equal(active()[[1]]$geom, "heatmap")
    expect_equal(active()[[1]]$limits, c(40, 60))
    expect_s3_class(plot(), "ggplot")
    session$setInputs(geom_t1 = "feature", fill_t1 = "kind", strand_t1 = "none", label_t1 = "", position_t1 = "inside", height_t1 = 0.12)
    expect_equal(active()[[1]]$geom, "feature")
    expect_equal(attr(plot(), "synteny_tracks")[[1]]$position, "inside")
    session$setInputs(axis = TRUE, axis_by = NA, axis_unit = "none", axis_position = "outside")
    expect_equal(vapply(active(), `[[`, "", "geom"), c("feature", "axis"))
    bad <- tempfile(fileext = ".tsv"); writeLines(c("start\tend", "x\t1"), bad)
    session$setInputs(add_file = list(datapath = bad, name = "bad.tsv"))
    expect_equal(length(active()), 2)
    expect_match(output$add_problem$html, "not added")
    session$setInputs(remove_t1 = 1)
    expect_equal(vapply(active(), `[[`, "", "geom"), "axis")
  })
})

test_that("the Synteny code builder can return only the figure-building lines", {
  d <- .studio_load("genes"); d <- .studio_select(d, d$organisms, 5)
  settings <- list(layout = "circular", palette = "casa_natal", alpha = 0.35, labels = TRUE,
                   orientation = FALSE, identity = FALSE, anchor = "body", gap = 10, title = NULL)
  lines <- .studio_code(d, settings, script = FALSE)
  expect_type(lines, "character")
  expect_true(any(grepl("^p <- plot_circular_microsynteny", lines)))
  expect_false(any(grepl("ggsave|library", lines)))
  expect_silent(parse(text = lines))
})
